;;;###autoload
(defun ub/insert-commit-prefix-w-emoji ()
  (interactive)
  (let* ((string-list
          '(":tada: init: "
            ":construction: wip: "
            ":christmas-tree: christmas tree bill (torba yasa)"
            ":bookmark: tag: "
            ":sparkles: feat: "
            ":bug: fix: "
            ":books: docs: "
            ":lipstick: style: "
            ":hammer: refactor: "
            ":rotating_light: test: "
            ":smiling-imp: customize:"
            ":wrench: chore:"
            ":ok_hand: review: "
            ":card_index: meta: "
            ;;":bulb: source: "
            ":racehorse: perf: "
            ":white_check_mark: addTest: "
            ":heavy_check_mark: passTest: "
            ":zap: update: "
            ":art: fmt: "
            ":fire: remove: "
            ":truck: move: "
            ":green_heart: ci: "
            ":lock: sec: "
            ":arrow_up: upDep: "
            ":arrow_down: downDep: "
            ":shirt: lint: "
            ;;":alien: i18n: "
            ;;":pencil: txt: "
            ":ambulance: hotfix: "
            ":rocket: deploy: "
            ":apple: fixMac: "
            ":penguin: fixLinux: "
            ":checkered_flag: fixWin: "
            ":construction_worker: ciBuild: "
            ":chart_with_upwards_trend: analytics: "
            ":heavy_minus_sign: removeDep: "
            ":heavy_plus_sign: addDep: "
            ":whale: docker: "
            ;;":wrench: config: "
            ;;":package: pkgJson: "
            ":twisted_rightwards_arrows: merge: "
            ":hankey: badCode: "
            ":rewind: revert: "
            ":boom: breaking: "
            ;;":wheelchair: a11y: "
            ))
         (selected-string (completing-read "Select a string: " string-list)))
    (insert selected-string)))
